-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 11:50:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinema` ;

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`people` ;

CREATE TABLE IF NOT EXISTS `cinema`.`people` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(64) NOT NULL,
  `nom` VARCHAR(64) NOT NULL,
  `date_naissance` DATE NULL DEFAULT NULL,
  `nationalite` CHAR(2) NULL DEFAULT NULL,
  `sexe` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`films` ;

CREATE TABLE IF NOT EXISTS `cinema`.`films` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(64) NOT NULL,
  `synopsis` TEXT NOT NULL,
  `date_sortie` DATE NOT NULL,
  `realisateur_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_films_people1_idx` (`realisateur_id`),
  CONSTRAINT `fk_films_people1`
    FOREIGN KEY (`realisateur_id`)
    REFERENCES `cinema`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`genre` ;

CREATE TABLE IF NOT EXISTS `cinema`.`genre` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`genre_assoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`genre_assoc` ;

CREATE TABLE IF NOT EXISTS `cinema`.`genre_assoc` (
  `genre_id` INT(10) UNSIGNED NOT NULL,
  `films_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`genre_id`, `films_id`),
  INDEX `fk_genre_has_films_films1_idx` (`films_id`),
  INDEX `fk_genre_has_films_genre1_idx` (`genre_id`),
  CONSTRAINT `fk_genre_has_films_films1`
    FOREIGN KEY (`films_id`)
    REFERENCES `cinema`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_has_films_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `cinema`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`play`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`play` ;

CREATE TABLE IF NOT EXISTS `cinema`.`play` (
  `films_id` INT(10) UNSIGNED NOT NULL,
  `people_id` INT(10) UNSIGNED NOT NULL,
  `personnage` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`films_id`, `people_id`),
  INDEX `fk_films_has_people_people1_idx` (`people_id`),
  INDEX `fk_films_has_people_films_idx` (`films_id`),
  CONSTRAINT `fk_films_has_people_films`
    FOREIGN KEY (`films_id`)
    REFERENCES `cinema`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_has_people_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `cinema`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`user` ;

CREATE TABLE IF NOT EXISTS `cinema`.`user` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cinema`.`whishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinema`.`whishlist` ;

CREATE TABLE IF NOT EXISTS `cinema`.`whishlist` (
  `user_id` SMALLINT(5) UNSIGNED NOT NULL,
  `films_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `films_id`),
  INDEX `fk_user_has_films_films1_idx` (`films_id`),
  INDEX `fk_user_has_films_user1_idx` (`user_id`),
  CONSTRAINT `fk_user_has_films_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_films_films1`
    FOREIGN KEY (`films_id`)
    REFERENCES `cinema`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
